[project]
name = "synthetic-qa-agent-hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=2.5.0",
    "pyyaml>=6.0.3",
    "tqdm>=4.67.1",
    "transformers>=4.57.1",
    "torch; sys_platform == 'linux'",
    "torchaudio; sys_platform == 'linux'",
    "torchvision; sys_platform == 'linux'",
    "unsloth>=2025.7.2",
    "unsloth-zoo>=2025.7.4",
]

[tool.uv.sources]
torch = { index = "rocm-nightly", marker = "sys_platform == 'linux'" }
torchaudio = { index = "rocm-nightly", marker = "sys_platform == 'linux'" }
torchvision = { index = "rocm-nightly", marker = "sys_platform == 'linux'" }

[[tool.uv.index]]
name = "rocm-nightly"
url = "https://rocm.nightlies.amd.com/v2/gfx94X-dcgpu/"
